# Generated by Django 3.0.3 on 2021-02-20 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210220_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=8), django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
